package com.example.docnet.enums;

public enum Speciality {
    MEDECIN_GENERALISTE, CARDIOLOGUE,
    DERMATOLOGUE,
    GYNECOLOGUE,
    PEDIATRE,
    OPHTALMOLOGUE,
    ORL,
    ORTHOPEDISTE,
    NEUROLOGUE,
    PSYCHIATRE,
    PNEUMOLOGUE,
    GASTROENTEROLOGUE,
    UROLOGUE,
    ENDOCRINOLOGUE,
    RADIOTHERAPEUTE,
    ANESTHESISTE,
    RADIOLOGUE,
    RHEUMATOLOGUE,
    CHIRURGIEN
}
